// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	domain "agent-cube/internal/domain"
	context "context"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentAPI is a mock of AgentAPI interface.
type MockAgentAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAgentAPIMockRecorder
	isgomock struct{}
}

// MockAgentAPIMockRecorder is the mock recorder for MockAgentAPI.
type MockAgentAPIMockRecorder struct {
	mock *MockAgentAPI
}

// NewMockAgentAPI creates a new mock instance.
func NewMockAgentAPI(ctrl *gomock.Controller) *MockAgentAPI {
	mock := &MockAgentAPI{ctrl: ctrl}
	mock.recorder = &MockAgentAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentAPI) EXPECT() *MockAgentAPIMockRecorder {
	return m.recorder
}

// InvokeAgent mocks base method.
func (m *MockAgentAPI) InvokeAgent(id, model string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvokeAgent", id, model)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokeAgent indicates an expected call of InvokeAgent.
func (mr *MockAgentAPIMockRecorder) InvokeAgent(id, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeAgent", reflect.TypeOf((*MockAgentAPI)(nil).InvokeAgent), id, model)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRubiksCube mocks base method.
func (m *MockRepository) CreateRubiksCube(ctx context.Context, cube domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRubiksCube", ctx, cube)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRubiksCube indicates an expected call of CreateRubiksCube.
func (mr *MockRepositoryMockRecorder) CreateRubiksCube(ctx, cube any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRubiksCube", reflect.TypeOf((*MockRepository)(nil).CreateRubiksCube), ctx, cube)
}

// GetAllRubiksCubes mocks base method.
func (m *MockRepository) GetAllRubiksCubes(ctx context.Context, limit int64) ([]domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRubiksCubes", ctx, limit)
	ret0, _ := ret[0].([]domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRubiksCubes indicates an expected call of GetAllRubiksCubes.
func (mr *MockRepositoryMockRecorder) GetAllRubiksCubes(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRubiksCubes", reflect.TypeOf((*MockRepository)(nil).GetAllRubiksCubes), ctx, limit)
}

// GetRubiksCubeByID mocks base method.
func (m *MockRepository) GetRubiksCubeByID(ctx context.Context, id primitive.ObjectID) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRubiksCubeByID indicates an expected call of GetRubiksCubeByID.
func (mr *MockRepositoryMockRecorder) GetRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRubiksCubeByID", reflect.TypeOf((*MockRepository)(nil).GetRubiksCubeByID), ctx, id)
}

// UpdateRubiksCube mocks base method.
func (m *MockRepository) UpdateRubiksCube(ctx context.Context, cube *domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCube", ctx, cube)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCube indicates an expected call of UpdateRubiksCube.
func (mr *MockRepositoryMockRecorder) UpdateRubiksCube(ctx, cube any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCube", reflect.TypeOf((*MockRepository)(nil).UpdateRubiksCube), ctx, cube)
}

// UpdateRubiksCubeStatus mocks base method.
func (m *MockRepository) UpdateRubiksCubeStatus(ctx context.Context, id primitive.ObjectID, status domain.RubiksCubeStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCubeStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCubeStatus indicates an expected call of UpdateRubiksCubeStatus.
func (mr *MockRepositoryMockRecorder) UpdateRubiksCubeStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCubeStatus", reflect.TypeOf((*MockRepository)(nil).UpdateRubiksCubeStatus), ctx, id, status)
}
