// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mock.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	domain "agent-cube/internal/domain"
	cube "agent-cube/internal/pkg/cube"
	context "context"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApplyRubiksCubeRotation mocks base method.
func (m *MockService) ApplyRubiksCubeRotation(ctx context.Context, cubeID primitive.ObjectID, rotation cube.Rotation) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRubiksCubeRotation", ctx, cubeID, rotation)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyRubiksCubeRotation indicates an expected call of ApplyRubiksCubeRotation.
func (mr *MockServiceMockRecorder) ApplyRubiksCubeRotation(ctx, cubeID, rotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRubiksCubeRotation", reflect.TypeOf((*MockService)(nil).ApplyRubiksCubeRotation), ctx, cubeID, rotation)
}

// CreateRubiksCube mocks base method.
func (m *MockService) CreateRubiksCube(ctx context.Context, llm domain.LLM, scramble int) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRubiksCube", ctx, llm, scramble)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRubiksCube indicates an expected call of CreateRubiksCube.
func (mr *MockServiceMockRecorder) CreateRubiksCube(ctx, llm, scramble any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRubiksCube", reflect.TypeOf((*MockService)(nil).CreateRubiksCube), ctx, llm, scramble)
}

// GetAllRubiksCubes mocks base method.
func (m *MockService) GetAllRubiksCubes(ctx context.Context, limit int64) ([]domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRubiksCubes", ctx, limit)
	ret0, _ := ret[0].([]domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRubiksCubes indicates an expected call of GetAllRubiksCubes.
func (mr *MockServiceMockRecorder) GetAllRubiksCubes(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRubiksCubes", reflect.TypeOf((*MockService)(nil).GetAllRubiksCubes), ctx, limit)
}

// GetRubiksCubeByID mocks base method.
func (m *MockService) GetRubiksCubeByID(ctx context.Context, id primitive.ObjectID) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRubiksCubeByID indicates an expected call of GetRubiksCubeByID.
func (mr *MockServiceMockRecorder) GetRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRubiksCubeByID", reflect.TypeOf((*MockService)(nil).GetRubiksCubeByID), ctx, id)
}

// IsRubiksCubeSolved mocks base method.
func (m *MockService) IsRubiksCubeSolved(ctx context.Context, cubeID primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRubiksCubeSolved", ctx, cubeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRubiksCubeSolved indicates an expected call of IsRubiksCubeSolved.
func (mr *MockServiceMockRecorder) IsRubiksCubeSolved(ctx, cubeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRubiksCubeSolved", reflect.TypeOf((*MockService)(nil).IsRubiksCubeSolved), ctx, cubeID)
}

// UpdateRubiksCube mocks base method.
func (m *MockService) UpdateRubiksCube(ctx context.Context, arg1 *domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCube", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCube indicates an expected call of UpdateRubiksCube.
func (mr *MockServiceMockRecorder) UpdateRubiksCube(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCube", reflect.TypeOf((*MockService)(nil).UpdateRubiksCube), ctx, arg1)
}

// UpdateRubiksCubeStatus mocks base method.
func (m *MockService) UpdateRubiksCubeStatus(ctx context.Context, id primitive.ObjectID, status domain.RubiksCubeStatus) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCubeStatus", ctx, id, status)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRubiksCubeStatus indicates an expected call of UpdateRubiksCubeStatus.
func (mr *MockServiceMockRecorder) UpdateRubiksCubeStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCubeStatus", reflect.TypeOf((*MockService)(nil).UpdateRubiksCubeStatus), ctx, id, status)
}
