// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mock.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	domain "agent-cube/internal/domain"
	cube "agent-cube/internal/pkg/cube"
	context "context"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockRubiksCubeService is a mock of RubiksCubeService interface.
type MockRubiksCubeService struct {
	ctrl     *gomock.Controller
	recorder *MockRubiksCubeServiceMockRecorder
	isgomock struct{}
}

// MockRubiksCubeServiceMockRecorder is the mock recorder for MockRubiksCubeService.
type MockRubiksCubeServiceMockRecorder struct {
	mock *MockRubiksCubeService
}

// NewMockRubiksCubeService creates a new mock instance.
func NewMockRubiksCubeService(ctrl *gomock.Controller) *MockRubiksCubeService {
	mock := &MockRubiksCubeService{ctrl: ctrl}
	mock.recorder = &MockRubiksCubeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRubiksCubeService) EXPECT() *MockRubiksCubeServiceMockRecorder {
	return m.recorder
}

// ApplyRubiksCubeRotation mocks base method.
func (m *MockRubiksCubeService) ApplyRubiksCubeRotation(ctx context.Context, cubeID primitive.ObjectID, rotation cube.Rotation) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRubiksCubeRotation", ctx, cubeID, rotation)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyRubiksCubeRotation indicates an expected call of ApplyRubiksCubeRotation.
func (mr *MockRubiksCubeServiceMockRecorder) ApplyRubiksCubeRotation(ctx, cubeID, rotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRubiksCubeRotation", reflect.TypeOf((*MockRubiksCubeService)(nil).ApplyRubiksCubeRotation), ctx, cubeID, rotation)
}

// CreateRubiksCube mocks base method.
func (m *MockRubiksCubeService) CreateRubiksCube(ctx context.Context, llm domain.LLM, scramble int) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRubiksCube", ctx, llm, scramble)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRubiksCube indicates an expected call of CreateRubiksCube.
func (mr *MockRubiksCubeServiceMockRecorder) CreateRubiksCube(ctx, llm, scramble any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRubiksCube", reflect.TypeOf((*MockRubiksCubeService)(nil).CreateRubiksCube), ctx, llm, scramble)
}

// DeleteRubiksCubeByID mocks base method.
func (m *MockRubiksCubeService) DeleteRubiksCubeByID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRubiksCubeByID indicates an expected call of DeleteRubiksCubeByID.
func (mr *MockRubiksCubeServiceMockRecorder) DeleteRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRubiksCubeByID", reflect.TypeOf((*MockRubiksCubeService)(nil).DeleteRubiksCubeByID), ctx, id)
}

// GetAllRubiksCubes mocks base method.
func (m *MockRubiksCubeService) GetAllRubiksCubes(ctx context.Context, limit int64) ([]domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRubiksCubes", ctx, limit)
	ret0, _ := ret[0].([]domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRubiksCubes indicates an expected call of GetAllRubiksCubes.
func (mr *MockRubiksCubeServiceMockRecorder) GetAllRubiksCubes(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRubiksCubes", reflect.TypeOf((*MockRubiksCubeService)(nil).GetAllRubiksCubes), ctx, limit)
}

// GetRubiksCubeByID mocks base method.
func (m *MockRubiksCubeService) GetRubiksCubeByID(ctx context.Context, id primitive.ObjectID) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRubiksCubeByID indicates an expected call of GetRubiksCubeByID.
func (mr *MockRubiksCubeServiceMockRecorder) GetRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRubiksCubeByID", reflect.TypeOf((*MockRubiksCubeService)(nil).GetRubiksCubeByID), ctx, id)
}

// IsRubiksCubeSolved mocks base method.
func (m *MockRubiksCubeService) IsRubiksCubeSolved(ctx context.Context, cubeID primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRubiksCubeSolved", ctx, cubeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRubiksCubeSolved indicates an expected call of IsRubiksCubeSolved.
func (mr *MockRubiksCubeServiceMockRecorder) IsRubiksCubeSolved(ctx, cubeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRubiksCubeSolved", reflect.TypeOf((*MockRubiksCubeService)(nil).IsRubiksCubeSolved), ctx, cubeID)
}

// RunAgent mocks base method.
func (m *MockRubiksCubeService) RunAgent(ctx context.Context, id primitive.ObjectID, llm domain.LLM) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAgent", ctx, id, llm)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAgent indicates an expected call of RunAgent.
func (mr *MockRubiksCubeServiceMockRecorder) RunAgent(ctx, id, llm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAgent", reflect.TypeOf((*MockRubiksCubeService)(nil).RunAgent), ctx, id, llm)
}

// StopAgent mocks base method.
func (m *MockRubiksCubeService) StopAgent(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopAgent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopAgent indicates an expected call of StopAgent.
func (mr *MockRubiksCubeServiceMockRecorder) StopAgent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAgent", reflect.TypeOf((*MockRubiksCubeService)(nil).StopAgent), ctx, id)
}

// UpdateRubiksCube mocks base method.
func (m *MockRubiksCubeService) UpdateRubiksCube(ctx context.Context, arg1 *domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCube", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCube indicates an expected call of UpdateRubiksCube.
func (mr *MockRubiksCubeServiceMockRecorder) UpdateRubiksCube(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCube", reflect.TypeOf((*MockRubiksCubeService)(nil).UpdateRubiksCube), ctx, arg1)
}

// UpdateRubiksCubeStatus mocks base method.
func (m *MockRubiksCubeService) UpdateRubiksCubeStatus(ctx context.Context, id primitive.ObjectID, status domain.RubiksCubeStatus) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCubeStatus", ctx, id, status)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRubiksCubeStatus indicates an expected call of UpdateRubiksCubeStatus.
func (mr *MockRubiksCubeServiceMockRecorder) UpdateRubiksCubeStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCubeStatus", reflect.TypeOf((*MockRubiksCubeService)(nil).UpdateRubiksCubeStatus), ctx, id, status)
}
