// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	domain "agent-cube/internal/domain"
	context "context"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentHub is a mock of AgentHub interface.
type MockAgentHub struct {
	ctrl     *gomock.Controller
	recorder *MockAgentHubMockRecorder
	isgomock struct{}
}

// MockAgentHubMockRecorder is the mock recorder for MockAgentHub.
type MockAgentHubMockRecorder struct {
	mock *MockAgentHub
}

// NewMockAgentHub creates a new mock instance.
func NewMockAgentHub(ctrl *gomock.Controller) *MockAgentHub {
	mock := &MockAgentHub{ctrl: ctrl}
	mock.recorder = &MockAgentHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentHub) EXPECT() *MockAgentHubMockRecorder {
	return m.recorder
}

// Deregister mocks base method.
func (m *MockAgentHub) Deregister(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deregister", id)
}

// Deregister indicates an expected call of Deregister.
func (mr *MockAgentHubMockRecorder) Deregister(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockAgentHub)(nil).Deregister), id)
}

// IsRunning mocks base method.
func (m *MockAgentHub) IsRunning(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockAgentHubMockRecorder) IsRunning(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockAgentHub)(nil).IsRunning), id)
}

// Register mocks base method.
func (m *MockAgentHub) Register(id string, cancel context.CancelFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", id, cancel)
}

// Register indicates an expected call of Register.
func (mr *MockAgentHubMockRecorder) Register(id, cancel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAgentHub)(nil).Register), id, cancel)
}

// Stop mocks base method.
func (m *MockAgentHub) Stop(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAgentHubMockRecorder) Stop(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentHub)(nil).Stop), id)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRubiksCube mocks base method.
func (m *MockRepository) CreateRubiksCube(ctx context.Context, cube domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRubiksCube", ctx, cube)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRubiksCube indicates an expected call of CreateRubiksCube.
func (mr *MockRepositoryMockRecorder) CreateRubiksCube(ctx, cube any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRubiksCube", reflect.TypeOf((*MockRepository)(nil).CreateRubiksCube), ctx, cube)
}

// DeleteRubiksCubeByID mocks base method.
func (m *MockRepository) DeleteRubiksCubeByID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRubiksCubeByID indicates an expected call of DeleteRubiksCubeByID.
func (mr *MockRepositoryMockRecorder) DeleteRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRubiksCubeByID", reflect.TypeOf((*MockRepository)(nil).DeleteRubiksCubeByID), ctx, id)
}

// GetAllRubiksCubes mocks base method.
func (m *MockRepository) GetAllRubiksCubes(ctx context.Context, limit int64) ([]domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRubiksCubes", ctx, limit)
	ret0, _ := ret[0].([]domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRubiksCubes indicates an expected call of GetAllRubiksCubes.
func (mr *MockRepositoryMockRecorder) GetAllRubiksCubes(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRubiksCubes", reflect.TypeOf((*MockRepository)(nil).GetAllRubiksCubes), ctx, limit)
}

// GetRubiksCubeByID mocks base method.
func (m *MockRepository) GetRubiksCubeByID(ctx context.Context, id primitive.ObjectID) (*domain.RubiksCube, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRubiksCubeByID", ctx, id)
	ret0, _ := ret[0].(*domain.RubiksCube)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRubiksCubeByID indicates an expected call of GetRubiksCubeByID.
func (mr *MockRepositoryMockRecorder) GetRubiksCubeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRubiksCubeByID", reflect.TypeOf((*MockRepository)(nil).GetRubiksCubeByID), ctx, id)
}

// UpdateRubiksCube mocks base method.
func (m *MockRepository) UpdateRubiksCube(ctx context.Context, cube *domain.RubiksCube) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCube", ctx, cube)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCube indicates an expected call of UpdateRubiksCube.
func (mr *MockRepositoryMockRecorder) UpdateRubiksCube(ctx, cube any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCube", reflect.TypeOf((*MockRepository)(nil).UpdateRubiksCube), ctx, cube)
}

// UpdateRubiksCubeStatus mocks base method.
func (m *MockRepository) UpdateRubiksCubeStatus(ctx context.Context, id primitive.ObjectID, status domain.RubiksCubeStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCubeStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCubeStatus indicates an expected call of UpdateRubiksCubeStatus.
func (mr *MockRepositoryMockRecorder) UpdateRubiksCubeStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCubeStatus", reflect.TypeOf((*MockRepository)(nil).UpdateRubiksCubeStatus), ctx, id, status)
}

// UpdateRubiksCubeUsage mocks base method.
func (m *MockRepository) UpdateRubiksCubeUsage(ctx context.Context, id primitive.ObjectID, usage domain.TokenUsage, totalCost float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRubiksCubeUsage", ctx, id, usage, totalCost)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRubiksCubeUsage indicates an expected call of UpdateRubiksCubeUsage.
func (mr *MockRepositoryMockRecorder) UpdateRubiksCubeUsage(ctx, id, usage, totalCost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRubiksCubeUsage", reflect.TypeOf((*MockRepository)(nil).UpdateRubiksCubeUsage), ctx, id, usage, totalCost)
}

// MockEventBus is a mock of EventBus interface.
type MockEventBus struct {
	ctrl     *gomock.Controller
	recorder *MockEventBusMockRecorder
	isgomock struct{}
}

// MockEventBusMockRecorder is the mock recorder for MockEventBus.
type MockEventBusMockRecorder struct {
	mock *MockEventBus
}

// NewMockEventBus creates a new mock instance.
func NewMockEventBus(ctrl *gomock.Controller) *MockEventBus {
	mock := &MockEventBus{ctrl: ctrl}
	mock.recorder = &MockEventBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBus) EXPECT() *MockEventBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventBus) Publish(ctx context.Context, event domain.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ctx, event)
}

// Publish indicates an expected call of Publish.
func (mr *MockEventBusMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventBus)(nil).Publish), ctx, event)
}
