[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.128.8",
    "langchain>=0.3.30",
    "langchain-openrouter>=0.2.3",
    "langfuse>=4.10.0",
]

[dependency-groups]
dev = [
    "pyyaml>=6.0.2",
    "ruff>=0.11.0",
    "ty",
]

[tool.ty.environment]
python = "./.venv"

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "W", "D213"]
ignore = ["D212"]

[tool.ruff.lint.pydocstyle]
convention = "google"
